{% set name = "Cerberus" %}
{% set version = "1.3.4" %}
{% set sha256 = "d1b21b3954b2498d9a79edf16b3170a3ac1021df88d197dc2ce5928ba519237c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7

  run:
    - python >=3.7
    - setuptools

test:
  requires:
    - pytest
  source_files:
    - cerberus/tests
  imports:
    - cerberus
    - cerberus.tests
  commands:
    - pytest cerberus/tests

about:
  home: https://github.com/nicolaiarocci/cerberus
  license: ISC
  license_file: LICENSE
  summary: Lightweight, extensible schema and data validation tool for Python dictionaries.

extra:
  recipe-maintainers:
    - fdosani
    - kyleniemeyer
