{% set name = "Cerberus" %}
{% set version = "1.3.2" %}
{% set sha256 = "302e6694f206dd85cb63f13fd5025b31ab6d38c99c50c6d769f8fa0b0f299589" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - cerberus
    - cerberus.tests
  commands:
    - pytest --pyargs cerberus

about:
  home: https://github.com/nicolaiarocci/cerberus
  license: ISC
  license_file: LICENSE
  summary: 'Lightweight, extensible schema and data validation tool for Python dictionaries.'

extra:
    recipe-maintainers:
        - fdosani
        - kyleniemeyer
